name: Deploy Infrastructure

on:
  workflow_dispatch: # Allows manual trigger of the workflow from the GitHub Actions UI

jobs:
  terraform:
    runs-on: ubuntu-latest  # Runs on a Linux environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Set up Terraform

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Import EC2'
        run: terraform import aws_instance.hands_on_hcl i-0cd5bf83263a8cbd3

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve

      # Step 7: Show imported resources
      - name: 'Terraform Show'
        run: terraform show
