name: Deploy Infrastructure

on:
  workflow_dispatch:  # Allows manual trigger of the workflow from the GitHub Actions UI

jobs:
  terraform:
    runs-on: ubuntu-latest  # Runs on a Linux environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Set up Terraform

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Verify Terraform folder
        run: ls -la  # Lists the content of the working directory to confirm folder structure

      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Run Terraform commands inside the terraform folder

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform  # Run Terraform commands inside the terraform folder

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform  # Run Terraform commands inside the terraform folder
